export const FOOD_DATA = {
  "hyderabadi-biryani": {
    id: "hyderabadi-biryani",
    name: "Biriyani Bliss",
    fullName: "Hyderabadi Biryani",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&q=80",
    rating: 4.8,
    reviews: 1050,
    price: 7.50,
    calories: "450 Cal",
    diameter: "15.05 Cm",
    description: "Hyderabadi biryani is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender meat, and tragrant basmati rice. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......",
  },
  "bombay-biryani": {
    id: "bombay-biryani",
    name: "Biriyani Bliss",
    fullName: "Bombay Biryani",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800&q=80",
    rating: 4.5,
    reviews: 1320,
    price: 8.50,
    calories: "380 Cal",
    diameter: "15.05 Cm",
    description: "Bombay biryani is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,mater and tragrant basmati rice. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......",
  },
  "onion-capsicum-pizza": {
    id: "onion-capsicum-pizza",
    name: "Pizza Bliss",
    fullName: "onion capsicum pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
    rating: 4.9,
    reviews: 1550,
    price: 10.50,
    calories: "480 Cal",
    diameter: "18.05 Cm",
    description: "Onion capsicum pizza is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender onion and capsicum and tragrant pizza base. originating from the vibrant city of the Hyaderabad in India, this is iconic dish......",
  },
  "panner-pizza": {
    id: "panner-pizza",
    name: "Pizza Bliss",
    fullName: "Panner and mater pizza",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    rating: 4.2,
    reviews: 1130,
    price: 9.50,
    calories: "460 Cal",
    diameter: "12.05 Cm",
    description: "Panner and mater pizza is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,mater and tragrant pizza base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......",
  },
  "veg-burger": {
    id: "veg-burger",
    name: "Burger Bliss",
    fullName: "Veg Burger",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    rating: 4.2,
    reviews: 1130,
    price: 12.50,
    calories: "560 Cal",
    diameter: "6.05 Cm",
    description: "Veg burger is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender aalu tiki and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......",
  },
  "paneer-burger": {
    id: "paneer-burger",
    name: "Burger Bliss",
    fullName: "Paneer Burger",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80",
    rating: 4.6,
    reviews: 1230,
    price: 8.50,
    calories: "460 Cal",
    diameter: "4.00 Cm",
    description: "Panner burger is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu tiki and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......",
  },
  "veg-sandwhic": {
    id: "veg-sandwhic",
    name: "Sandwhic Bliss",
    fullName: "Veg Sandwhic",
    image: "https://images.unsplash.com/photo-1528733918455-5a59687cedf0?w=800&q=80",
    rating: 4.6,
    reviews: 1230,
    price: 7.50,
    calories: "460 Cal",
    diameter: "4.00 Cm",
    description: "Veg sandwhic is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......",
  },
  "potato-sandwhic": {
    id: "potato-sandwhic",
    name: "Sandwhic Bliss",
    fullName: "Potato Sandwhic",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80",
    rating: 4.6,
    reviews: 1343,
    price: 6.50,
    calories: "460 Cal",
    diameter: "4.00 Cm",
    description: "Potato sandwhic is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish......",
  }
}
